# -*- coding: utf-8 -*-
"""histo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fw-UGqh_C6v7CozS5Kr-rtLv1nLOJDCB
"""

import math
tmp = []
inttmp = []
total = []
prob = []
probsum = []
histo = []

with open("HistogramEQ.bmp", "rb") as f:
    byte = f.read(1)
    while byte != b"":
        # Do stuff with byte.
        tmp.append(byte)
        byte = f.read(1)

for i in range(len(tmp)):
    inttmp.append((int.from_bytes(tmp[i], "big")))

for i in range(256):
    total.append(0)

for i in range(1078,len(inttmp)):
    total[inttmp[i]] += 1

for i in range(256):
    prob.append(float(total[i]) / (len(inttmp)-1078))

sum = 0.0
for i in range(256):
    probsum.append(sum + prob[i])
    sum += prob[i]

for i in range(1078,len(inttmp)):
    histo.append(int(probsum[inttmp[i]] * 255) )

f.close()

res = open("histo.bmp","wb+")

res.write(bytes(inttmp[0:1078]))
res.write(bytes(histo))

res.close

