# -*- coding: utf-8 -*-
"""logarithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZpKBoLC-p6kPxVOy91yrxVucWPPhBcN4
"""

import math
tmp = []
inttmp = []
log = []
c = 30

with open("logarithm.bmp", "rb") as f:
    byte = f.read(1)
    while byte != b"":
        # Do stuff with byte.
        tmp.append(byte)
        byte = f.read(1)

print(int.from_bytes(tmp[1079], "big") )

for i in range(len(tmp)):
    inttmp.append(int.from_bytes(tmp[i], "big"))

for i in range(1078,len(inttmp)):
    if(inttmp[i] != 0):
        log.append(int(c * math.log(1 + inttmp[i]  )))
    else:
        log.append(0)

f.close()

res = open("log.bmp","wb+")

res.write(bytes(inttmp[0:1078]))
res.write(bytes(log))

res.close