# -*- coding: utf-8 -*-
"""power.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SduGilnTlgC1tFxcY0zACmPpiFmV5js2
"""

import math
tmp = []
inttmp = []
c = 255
r = 1.8



with open("power_law.bmp", "rb") as f:
    byte = f.read(1)
    while byte != b"":
        # Do stuff with byte.
        tmp.append(byte)
        byte = f.read(1)

for i in range(len(tmp)):
    inttmp.append((int.from_bytes(tmp[i], "big")))

power = []
powerint = []

for i in range(1078,len(inttmp)):
    power.append(c * pow(float(inttmp[i]) / 255 ,r))

for i in range(len(power)):
    powerint.append(int(power[i]))

f.close()

res = open("power.bmp","wb+")

res.write(bytes(inttmp[0:1078]))
res.write(bytes(powerint))

res.close